### ISSUE TITLE
Embedding model fails to load in Electron - transformers.node.mjs ERR_MODULE_NOT_FOUND (v0.19.0+)

### ISSUE THREAD

**Issue by wwth8819** [cortexkit/opencode-magic-context#78]
## What happened
After upgrading from v0.17.0 to v0.19.0, the local embedding model (Xenova/all-MiniLM-L6-v2) fails to load on every 15-minute timer tick.

## Error log
[magic-context] embedding model failed to load: Cannot find module 'C:\Users\13096\.cache\opencode\packages\@cortexkit\opencode-magic-context@latest\node_modules\@huggingface\transformers\dist\transformers.node.mjs' imported from C:\Users\13096\.cache\opencode\packages\@cortexkit\opencode-magic-context@latest\node_modules\@cortexkit\opencode-magic-context\dist\index.js
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '...transformers.node.mjs'

## What I expected
Embedding model loads normally as it did in v0.17.0.

## Repro steps
1. Upgrade MC plugin from v0.17.0 to v0.19.0 via doctor --force + restart OpenCode Desktop
2. Check magic-context.log — embedding fails every 15 minutes on timer tick
3. The file transformers.node.mjs exists on disk at the specified path, but Node.js ESM resolver cannot find it

## Environment
- OpenCode Desktop v1.14.33 (Electron 34.3.0, Node ABI 145)
- Windows 11
- MC v0.19.0 (plugin cache)
- @huggingface/transformers v4.2.0
- Embedding config: local (Xenova/all-MiniLM-L6-v2 bundled)

## Notes
- Doctor check passes 14/14 (config-level check only)
- All other MC features work fine (transform, historian, dreamer, ctx_reduce)
- The file exists on disk — this appears to be an ESM module resolution issue specific to Electron environment

**Comment by wwth8819** [comment]
[magic-context-issue-20260516-010152.md](https://github.com/user-attachments/files/27809813/magic-context-issue-20260516-010152.md)

**Comment by ualtinok** [comment]
This should be fixed in v0.21.0, please let me know if the problem persists.

**Comment by Number16BusShelter** [comment]
issue still seems to be present on version v0.21.6

```
[magic-context] embedding model failed to load: {"name":"ResolveMessage","position":null,"message":"Cannot find module '@huggingface/transformers' from '/.cache/opencode/packages/@cortexkit/opencode-magic-context@latest/node_modules/@cortexkit/opencode-magic-context/dist/index.js'","level":"error","specifier":"@huggingface/transformers","importKind":"import-statement","referrer":"/.cache/opencode/packages/@cortexkit/opencode-magic-context@latest/node_modules/@cortexkit/opencode-magic-context/dist/index.js"}
```

**Comment by ualtinok** [comment]
Thats odd: did the issue resolved for you @wwth8819 ?

**Comment by wwth8819** [comment]
> Thats odd: did the issue resolved for you [@wwth8819](https://github.com/wwth8819) ?奇怪：问题解决了吗？

For me, this problem has been resolved.   OC: 1.15.6 MC:v0.21.6

**Comment by ualtinok** [comment]
@Number16BusShelter can you open a new issue via
```
npx @cortexkit/magic-context@latest doctor --issue
```

**Comment by wwth8819** [comment]
> Thats odd: did the issue resolved for you [@wwth8819](https://github.com/wwth8819) ?

But there are still issues with Embedding (it has been assigned the wrong type): 
embedding model failed to load: Unsupported device: "cpu". Should be one of: .
Version 0.21.0's fix solution was to inject onnxruntime-web into the Electron environment. However, the package.json exports structure of onnxruntime-web is incompatible with the new version, resulting in: 
The "onnxruntime-web/package.json" file cannot be resolved → Switching to the WASM path
Device: "cpu" is not supported (the device list is empty)
This is a compatibility bug for the @huggingface/transformers v4.2.0 + onnxruntime-web combination. The core functionality is not affected.
